- name: Update apt package index
  apt:
    update_cache: yes
- name: Install Docker
  apt:
    name:
      - docker.io
    state: present
- name: Install Docker Compose
  apt:
    name:
      - docker-compose
    state: present
- name: Clone the GitHub repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ directory_dest }}"
    update: yes
- name: Bring down Docker Compose services
  shell: "docker-compose down"
  args:
    chdir: "{{ directory_dest }}"
- name: Delete all stopped containers
  shell: docker container prune -f
  ignore_errors: yes
- name: Delete all unused images
  shell: docker image prune -a -f
  ignore_errors: yes
- name: Change the directory and start the application
  shell: "docker-compose up -d"
  args:
    chdir: "{{ directory_dest }}"
  register: compose_status
- name: Debug Docker Compose output
  debug:
    var: compose_status

