- name: Update apt package index
  apt:
    update_cache: yes
- name: Install Docker
  apt:
    name:
      - docker.io
    state: present
- name: Try to start a basic image in docker
  docker_container:
    name: hello-world
    image: hello-world
    state: started
    recreate: no
- name: Install Docker Compose
  apt:
    name:
      - docker-compose
    state: present
- name: Clone the GitHub repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ directory_dest }}"
    update: yes
- name: Delete all images available 
  shell: "docker rmi $(docker images -a -q)"
- name: Bring down Docker Compose services
  shell: "docker-compose down"
  args:
    chdir: "{{ directory_dest }}"
- name: Change the directory and start the application
  shell: "docker-compose up -d"
  args:
    chdir: "{{ directory_dest }}"
  register: compose_status
- name: Debug Docker Compose output
  debug:
    var: compose_status

